version: "3"
services:
  db:
    image: postgres
    restart: unless-stopped
    environment:
      TZ: America/Sao_Paulo
      POSTGRES_DB: mydb2
      POSTGRES_USER: marola
      POSTGRES_PASSWORD: marola
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    networks:
      - postgres-network
volumes:
  db-data:
    driver: local

networks:
  postgres-network:
    driver: bridge
